vich_uploader:
    db_driver: orm
    twig: true # set to false to disable twig integration
    form: true # set to false to disable form integration
    storage: file_system # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
        type: attribute # or annotation
    mappings:
        pages_images:
            uri_prefix: /images/pages
            upload_destination: "%kernel.project_dir%/public/images/pages"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        produits:
            uri_prefix: /images/produits
            upload_destination: "%kernel.project_dir%/public/images/produits"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        sliders:
            uri_prefix: /images/sliders
            upload_destination: "%kernel.project_dir%/public/images/sliders"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
